language: python
sudo: enabled
dist: trusty
python:
  - "3.6"
services:
  - mysql
env:
  - DJANGO_VERSION=1.11.2
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install mysqlclient
script:
  - python setup.py
  - python manage.py makemigrations polls
  - python manage.py migrate
  - python manage.py runserver &
  - django_server_pid=$!
  - kill -SIGINT $django_server_pid
